### ISSUE TITLE
Cassandra Order By

### ISSUE THREAD

**Issue by alpernakin** [tomncooper/CSC8101-Documentation#10]
Hello, I got a problem with ordering in Cassandra. When I want to query with "order by", it gives that error:  "Error from server: code=2200 [Invalid query] message="ORDER BY is only supported when the partition key is restricted by an EQ or an IN."
I have checked possible solutions on documentation. After I read documentation, I applied "with clustering order by (timestamp desc)" just creating the table in order to fix this. Yet, it did not work, Can you please help with this?

**Comment by tomncooper** [comment]
As you have found, you cannot use ORDER By in a Cassandra query, except on the partition key. 

If your primary key has timestamp as the first item (the partition key) then your WITH CLUSTERING ORDER BY timestamp will make no difference. 

You are on the right track that you need to use WITH CLUSTERING ORDER BY in your table schema, you just need to decide which fields need to be in the ordering. You can only order by fields that are in your PRIMARY KEY. You can order by several fields and define them as ascending or descending. 

I suggest you create some test tables in `cqlsh` and add some simple sample data to test your schema.

**Comment by alexbfree** [comment]
@tomncooper (or any other demonstrators) I am also struggling with this issue, in trying to select the last three batch periods.

I want to do something like (in SQL) `SELECT DISTINCT batchStart FROM hits ORDER BY batchStart DESC LIMIT 3;`

I have understood that if I want to `SELECT DISTINCT` on `batchStart`, then `batchStart` has to be my partition key.
But I have also understood that if I want to `ORDER BY batchStart`, then `batchStart` has to be NOT part of the partition key, but part of the compound/clustering key.

I am unsure how to resolve this kind of conflict, when your query demands two conflicting table structures... so now i am thinking maybe I need a separate table just to track what the last three batch start times are... this seems like it is not the right way to go. Any advice? 
I know i could possibly calculate the time windows, but i am reluctant to make assumptions about the data coming in, that seems bad practice....

**Comment by tomncooper** [comment]
@alexbfree You should avoid using `DISTINCT` and `ORDER BY` in Cassandra queries. You should use your table schema (how the data is written to the database) to simplify your query. 

If you only want only distinct timestamps then you could create a separate table which only stores timestamps (repeated entries with the same key would overwrite each other). Then it is a very simple `SELECT * FROM timestamp_table LIMIT 3`. This is just an example, you may wish to include other fields in your separate timestamp table.

**Comment by alexbfree** [comment]
Thanks. I guess the relational database part of my brain is telling me not to create extra tables - but in Cassandra-land this is quite normal and indeed good practice...

**Comment by alexbfree** [comment]
Out of interest why does Cassandra support these things if it's not advisable to use them?

**Comment by tomncooper** [comment]
It only supports them from very specific situations. 

Distinct only working for the partition key is really just a side effect of how they are indexing the partition keys, not that they designed a specific distinct feature. 

Order by in selects only works for elements in the primary key as they are already ordered (according to their natural order) by default.

**Comment by alexbfree** [comment]
Good to know, thanks.

**Comment by alpernakin** [comment]
Thanks for your help Tom. But, my problem on this issue is still going on.
"Order by in selects only works for elements in the primary key as they are already ordered (according to their natural order) by default". I try "order by" for fields which are already in primary key (not partition key), but it does not work again.

**Comment by alexbfree** [comment]
@alpernakin I don't know if this helps - but I found that when you use WITH CLUSTERING ORDER BY in your table definition, then you can just entirely omit any ORDER BY from your SELECT query, and everything works - the ordering comes from the table, not the query....

**Comment by alpernakin** [comment]
@alexbfree Thank you for your suggestion. I solved this problem with a different way. As Tom told, I just avoid using order by in Cassandra.
