### ISSUE TITLE
Questions about approach to subqueries and temporary tables in Cassandra

### ISSUE THREAD

**Issue by alexbfree** [tomncooper/CSC8101-Documentation#13]
Hi

I see that you can't do subqueries in Cassandra.
I was wanting to do something like

select page from hits where clientID=? and topic=? and batchperiodstart in (SELECT batchPeriodStart FROM batchPeriods WHERE clientID=? AND topic=? LIMIT 3)

I guess my only option is to populate a temporary table with the results of the subquery, and then do a join between the hits table and the temporary table? Just wanted to check I am on the right lines as to whether that is the right way to go?

Can you tell me what is the Cassandra equivalent of "SELECT INTO" to actually put the query results into a temporary table? (i've extracted this question into a separate issue #14)

Also, I am getting the impression that you quickly end up with lots of duplication of data in Cassandra given the one-table-per-query idea.... what is the etiquette (and expectations for this assignment) in terms of keeping the data in sync across your tables? 
I guess you would just re-populate any temporary tables as part of the algorithm just prior to running a query? Is that a reasonable way to do it? Do you need to check through the temporary table to delete old, no longer needed rows each time? Or maybe just wipe the whole temp table each time? Or maybe it is better to not worry about the tables getting bigger and bigger, and just keep on appending and only use the most recent rows?

Also are queries synchronous in Cassandra? If you run a query to populate a temporary table - then execute a query joining onto that table, is it safe to assume the table will now be populated? Or do we need to do some sort of locks or transactions or something if we are running queries that depend on the previous one having completed?

Hope you can point me in the right direction. Thanks.

**Comment by alexbfree** [comment]
I think the answer to #14 has partly answered my question... in that I guess I need to think in a different mindset to SQL where you normally try and do as much as possible in the query... and here you should do more in the code. so maybe i don't need temporary tables. (still interested to know thoughts about synchronicity and sequential queries though)

I suppose that leaves the question, how on earth do we make this scale? If writing an intermediate query's results to a different table requires the code to go through every row of the resultset, and execute a new query, can that even work if you give it tens of thousands of records in the resultset?

**Comment by tomncooper** [comment]
You need to forget what your learned about relational databases. Writes are cheap in Cassandra. Have as many tables as you want. In your example your temp table is just another table, you will insert data into it at  the same time as the other table and its schema does any ordering etc that you would usually do in a query. Remember, the table schema will do the hard work for you so that the queries are simple.

Cassandra scales incredibly well (that is why it is included in a Big Data course). The many tables, cheap writes and simple queries approach means it is very fast for the relatively simple queries most employed in its domain. If you have to do complex table joins and relational logic you would not use Cassandra for that application and you do not need to do that for this coursework.

**Comment by alexbfree** [comment]
Thank you for the explanation. My mindset is shifting now to the Cassandra way of thinking and this was really helpful in getting me there.

I do have one (hopefully last) question in this space... for task 3 I am trying to determine the "most recent batch". Since we know nothing about what sizes of time windows or batches we will be passed, or when they might start, it seems appropriate that I would determine this from the data rather than from the current time or anything like that.

Therefore I was thinking I would do something like using LIMIT 1 to just select the first entry from something ordered by batch time in descending order.
The problem is that as far as I can see you can't sort on the partition key (I was thinking of having a separate table just for this query, with batchStartTime as partition key).. but the rows are not ordered. On the other hand, if I partition by something else such as topic or clientID, then I can order by descending batch time (WITH CLUSTERING ORDER BY batchStartTime DESC) ... but now I no longer have confidence that getting the first batch time in this partition is the most recent across the whole dataset... if partitioned by client, another user may have logged on more recently than the one I picked... if partitioned by topic, another topic may have been visited more recently than the one I picked.

Can you advise/give me any clues on how I can derive "most recent batch" across all clients and topics from the data? I can't seem to find a table structure that will let me query this... 

Or maybe we are supposed to assume that most recent batch doesn't mean "most recent in time" but rather "most recent for this user" or "most recent for this page" or "most recent for this topic"?

Thanks again for your help

**Comment by tomncooper** [comment]
You are on the right track with a separate timestamp table. If your timestamp is a big int unix time and the primary key is just the timestamp then the table will only contain unique timestamps (accross all client ids and topics) and will automatically order the timestamps from lowest number (earliest time) to highest unless you redefine the ordering as you suggest. No need for sorting. 

If you want the most recent timestamp for a given client you will need more fields and a different primary key.

**Comment by alexbfree** [comment]
> will automatically order the timestamps from lowest number (earliest time) to highest

Hmm, that's odd. I tested this, inserting a few records with different timestamps in a random order, and when I listed the table it seemed to be stored in the order of insertion, not the order of the data.

My table declaration was 
`CREATE TABLE periods (batchPeriodStart bigint, PRIMARY KEY (batchPeriodStart));`

the records are not in data order

<img width="150" alt="screenshot 2017-02-27 14 55 00" src="https://cloud.githubusercontent.com/assets/1473244/23365914/ca4b6e8a-fcfc-11e6-97f1-53903f81351e.png">

What am I missing?

**Comment by tomncooper** [comment]
Humm, that is odd. What happens when you force the cluster ordering? 

Also what program are you viewing your results in? That doesn't look like `cqlsh` or a Jupyter notebook?

**Comment by ttgilbert** [comment]
Tom, I'm having the same issue. It doesn't auto order and forced ordering is only possible on clustering keys, not partition keys - and if there's only one column of timestamps then it has to be the partition key, as far as I'm aware. Also, DISTINCT is only possible on partition keys, so I'm a bit stumped with how to achieve this purely with queries and tables, and not resorting to client-side processing (or some kind of dummy column for the timestamps table).

**Comment by tomncooper** [comment]
You may want to choose a different partition key then, perhaps client id? If you have both client id and timestamp in this table and order by timestamp you will be able to find the most recent timestamps per client. 

A quick google brings up [this](http://www.datastax.com/dev/blog/we-shall-have-order) DataStax (the guys who make Cassandra) article with some useful pointers and common pitfalls.

**Comment by tomncooper** [comment]
You may want to choose a different partition key then, perhaps client id? If you have both client id and timestamp in this table and order by timestamp you will be able to find the most recent timestamps per client.

A quick google brings up [this](http://www.datastax.com/dev/blog/we-shall-have-order) DataStax (the guys who make Cassandra) article with some useful pointers and common pitfalls.

**Comment by ttgilbert** [comment]
Tom, the coursework spec doesn't seem to care about most recent timestamps featuring in a client's visit profile; my interpretation is that we care about excluding pages visited by clients where this visit falls in one of the globally most recent timestamps (" ...exclude any pages that the Client ID has visited in the last 3 time periods."). So, a client's most recent three might include two from last week, but the most recent three timestamps featuring in the database are all from the last hour (or even last minute), so those client visits last week cannot cause exclusions. So I want to find a unique list of ordered timestamps appearing anywhere in the database. Unless, of course, I've misinterpreted!

**Comment by tomncooper** [comment]
The spec is open to interpretation by design. 

If the client hasn't visited for 2 weeks then maybe pages they have already visited should not be excluded from the recommendations? However maybe that is not true to the recommendation algorithm and recommending already visited pages is not so useful regardless of how long ago the client last visited them? 

Provided your interpretation is sensible and you can defend it in the viva we will only be marking you on how well you have implemented it.

**Comment by ttgilbert** [comment]
Ok, thanks! It's certainly getting me thinking.

**Comment by alexbfree** [comment]
in reply to @tomncooper 

> Also what program are you viewing your results in? That doesn't look like cqlsh or a Jupyter notebook?

That was DBeaver. Here is the same in cqlsh:

```
cqlsh:csc8101> DROP TABLE testPeriods;
cqlsh:csc8101> CREATE TABLE testPeriods (batchPeriodStart bigint, PRIMARY KEY (batchPeriodStart));
cqlsh:csc8101> insert into testperiods(batchperiodstart) VALUES(1455560655);
cqlsh:csc8101> insert into testperiods(batchperiodstart) VALUES(1455559155);
cqlsh:csc8101> insert into testperiods(batchperiodstart) VALUES(1455561155);
cqlsh:csc8101> insert into testperiods(batchperiodstart) VALUES(1455559655);
cqlsh:csc8101> insert into testperiods(batchperiodstart) VALUES(1455560155);
cqlsh:csc8101> insert into testperiods(batchperiodstart) VALUES(1455560655);
cqlsh:csc8101> select * from testperiods;

 batchperiodstart
------------------
       1455560155
       1455560655
       1455559155
       1455559655
       1455561155

(5 rows)
cqlsh:csc8101> select batchperiodstart from testperiods limit 1;

 batchperiodstart
------------------
       1455560155

(1 rows)
cqlsh:csc8101>
```

Note that this is neither the most recent timestamp (1455561155) nor the earliest timestamp (1455559155) but is in fact the last timestamp inserted (1455560655) suggesting the field is unordered.

>Humm, that is odd. What happens when you force the cluster ordering?

Not allowed:
```
cqlsh:csc8101> CREATE TABLE testPeriods (batchPeriodStart bigint, PRIMARY KEY (batchPeriodStart)) WITH CLUSTERING ORDER BY (batchPeriodStart DESC);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Only clustering key columns can be defined in CLUSTERING ORDER directive"
```

Hope you can advise how I can take advantage of this partition key ordering.. if not then I guess I could make up some meaningless partition key for every record so everything gets put in the same partition, then I can have batch period as the clustering key instead which will allow ordering.

**Comment by alexbfree** [comment]
@tomncooper (or other demonstrators) can you advise on this?

(for now I'm justing using "most recent per topic" but would like to improve on this if I can)

**Comment by tomncooper** [comment]
As per my comment to ttgilbert above, you may use whatever approach you wish to address the specification provided it is a sensible interpretation, provides an outcome that meets your interpretation of the specification and you can defend your decisions.

**Comment by alexbfree** [comment]
Right. I was really asking you about the capabilities of Cassandra. But no worries, I appreciate you have spent a lot of time pointing me on the right track! Closing ticket.
