### ISSUE TITLE
Urgent: How do you SELECT INTO a temp table in Cassandra?

### ISSUE THREAD

**Issue by alexbfree** [tomncooper/CSC8101-Documentation#14]
I've extracted this simple question from my longer issue #13 as I need to know this more urgently.

I can't seem to find how we put the results of a SELECT query into another table. Do you have to do it in code (processing the results and issuing new insert queries) or is there a way to do in a query?

Thanks
Alex

**Comment by tomncooper** [comment]
Hi Alex, if you want to do this then do a select using the API (Python for example) then again use the API to insert the returned results of the select into the other table.

**Comment by alexbfree** [comment]
OK. no way to do it within the query language then. thanks.
