### ISSUE TITLE
Please clarify Cassandra Task 2

### ISSUE THREAD

**Issue by alexbfree** [tomncooper/CSC8101-Documentation#15]
For Cassandra Task 2, it says 
>To satisfy task 2, write a CQL query to list the top N Pages ranked by visitor count for a given Topic and time period. 

Could you clarify what "time period" means here? Does that mean a specific batch start time will be specified? Or an arbitrary time range, with a start and end (so we would need to add together all the batches that fall in that time range)?

If the latter, and given we don't know batch length, can we just assume that any batch starting within the specified range should be included?

Thanks

**Comment by tomncooper** [comment]
The upstream system will tag every entry with the minimum timestamp seen in all the messages received in the window. Therefore for the Cassandra coursework the "time period" refers to the single timestamp that all entries from a given batch will have.

**Comment by alexbfree** [comment]
great, thanks
