### ISSUE TITLE
Spark_task7 what means highly rated 

### ISSUE THREAD

**Issue by XuHuan0217** [tomncooper/CSC8101-Documentation#16]
In Spark task7 question 3.

> For a given actor, returns users who highly rate movies in which their co-stars appear, but who has never rated a movie in which this actor has appeared.

I'm confused on the meaning of highly rate. What should be the threshold of highly rate (>=4 or >=5)? 
And for a given actor, he/she may have lots co-stars, so, is this question means the target users should 'highly rate' on all their movies? or just a subset of those movies? 
If the user must rate on all the movies which the co-starts appear, then its quite difficult to find one.

**Comment by hugofirth** [comment]
Hi @XuHuan0217,

Given the first query you are asked to write, Task 7 generally assumes that you take any rating >= 4.0 to be **high**. On the other hand, the wording is vague, so any value you can defend at viva time is fine (i.e. probably not 2.0 but ...).

As for the second part of your question: The query is meant to indicate users who have highly rated **any** movie in which a co-star appears, but **none** in which the actor themselves appears (alongside a co-star or not is irrelevant).

I hope that helps.

**Comment by XuHuan0217** [comment]
Thanks, its help a lot
