### ISSUE TITLE
CLUSTER IP (How to run streaming job in cluster)

### ISSUE THREAD

**Issue by cheburan** [tomncooper/CSC8101-Documentation#17]
Could you please say IP(s) for the cluster, to run streaming job in it? 
If I understood it right, console command for running *.py file stays the same as in local case?

**Comment by tomncooper** [comment]
Hi,

Sorry that the IP address was not in the docs. I have updated the coursework spec with instructions on how to connect to the cluster.

The IP address is 52.213.206.26. If you are using the stub file just change the `master=` argument at the top of the file. The spark submit call is the same as for running locally.

**Comment by PetoMichalak** [comment]
Also, Spark batch part of the coursework [Task 0](https://github.com/tomncooper/CSC8101-Documentation/blob/master/spark/spark-coursework-spec.md#task-0) has a link to a guide: [steps for local and cluster deployment](https://github.com/tomncooper/CSC8101-Documentation/blob/master/spark/python-stub/python-deployment.md). From here you can find how to check whether the cluster master node is up and instructions how to submit a job to it.

This cluster can be used for Spark Streaming and Spark batch part of the coursework.

**Comment by alexbfree** [comment]
What is the correct format for the `master=` argument? we're seeing an error parsing the address with both `master="52.213.206.26"` and `master="52.213.206.26[2]"`
