### ISSUE TITLE
Task 6 Neo4j

### ISSUE THREAD

**Issue by ZayyadGaya** [tomncooper/CSC8101-Documentation#18]
Only a few data get loaded into neo4j database.

**Comment by tomncooper** [comment]
We will need a bit more information. 

Have you loaded the graph.tgz file as specified in the coursework spec or are you talking about writing your own data to Neo4j as in Task 6?

**Comment by ZayyadGaya** [comment]
Yes, I mean Task6. I can see the data I loaded but very few.
I have dropped the data multiple times and loading graph.tgz and then mine I still get very few data.

**Comment by PetoMichalak** [comment]
Hi,

first of all, can you confirm that you are using model produced in Task 2 to predict ratings for entries in `qualifying_simple.txt` dataset? This dataset has over 2.8 million records from which we are asking you to randomly select 5% to inject into your neo4j database.

Can you provide:
* [element count](http://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.RDD.count) after you load `qualifying_simple.txt` into RDD,
* number of elements after you use your model to predict ratings on this file,
* number of users or relationships which you have inserted into your database? 

This should help us to narrow down the point where you might be loosing any records.

**Comment by ZayyadGaya** [comment]
After loading the qualifying_simple.txt my data is 2817131
After the prediction, I have 2712506 data
And the 5% of my sample is 135887 data
When loading to neo4j I convert the rdd in a dictionary and load all to neo4j, but only a few get loaded.
I also tried sending the data in rdd form using collect, but still only a few get loaded.
I tried loading just about 20,000 data using take() in rdd form, but only a few get loaded even fewer than when using collect().

**Comment by PetoMichalak** [comment]
Thanks for the clarification on this.

This shifts our focus on the way you define your neo4j statements. When you're creating a relationship from a User to a Movie are you using a movie title or movie id?

> Note that you should only attempt to write ratings to Neo4j if the rating's movie id corresponds to a movie title which already exists in the Neo4j database (Hint: remember your alias map from Task 1).  - [Task 6](https://github.com/tomncooper/CSC8101-Documentation/blob/master/spark/spark-coursework-spec.md#task-6-)

**Comment by ZayyadGaya** [comment]
I joined my 5% sample with my alias title in task1.

**Comment by PetoMichalak** [comment]
Can you manually verify movie titles of few records you are trying to insert?

```cql
MATCH (n {title:"Independence Day"}) RETURN n
```

**Comment by ZayyadGaya** [comment]
I have dropped the data from neo4j again, but I will reboot my VM, run the model and then load data to neo4j. It may take at least 30-40 minutes before I give a feedback.

**Comment by ZayyadGaya** [comment]
I finally got something. Thank you, I really appreciate the help.
