### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by alexchet** [tomncooper/CSC8101-Documentation#2]
For task 4 when I run the ALS.train of the full data file or the predict all on the model, the computation take a ridiculous amount of time around maybe around 40 mins. 

When I tried to run "metrics.rootMeanSquaredError", the computation took around 3hrs+. 

Is this any fault of mine or is it just the size of the data we are working with? 

Also for predict all the shell keeps getting the following errors until it is finished.
17/02/13 14:38:00 WARN MemoryStore: Not enough space to cache rdd_31_32 in memory! (computed 21.6 MB so far)

Thanks

**Comment by PetoMichalak** [comment]
Hi,

you can try increasing the memory available to your spark executors. In case you are using iPython notebooks, run pyspark command with additional parameters, e.g.:

```
$ pyspark --num-executors 5 --driver-memory 2g --executor-memory 2g
```

A paragraph in [Task 0](https://github.com/tomncooper/CSC8101-Documentation/blob/master/spark/spark-coursework-spec.md#task-0) touches on this.

Let us know if this resolved your problem!

**Comment by alexchet** [comment]
Hi,

Yes it did solve my problem, thanks for the suggestion.
Also I was using the wrong RDD for the predictions.

Thanks
