### ISSUE TITLE
Streaming part (Cluster)

### ISSUE THREAD

**Issue by cheburan** [tomncooper/CSC8101-Documentation#20]
I tried your suggestion from the issue #17 (CLUSTER IP)
<code>
SC = SparkContext(master="52.213.206.26", appName="Event Processing", conf=sp_conf)
</code>

But, I've got error: 
<code>
ERROR SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: Could not parse Master URL: '52.213.206.26'
</code>

**Comment by PetoMichalak** [comment]
Hi,

you have a couple of options here. [Master URLs format](http://spark.apache.org/docs/latest/submitting-applications.html#master-urls) can be passed directly to `spark-submit` command when submitting the job to the cluster, e.g.:

```bash
$ spark-submit --master spark://ip-172-31-25-107.eu-west-1.compute.internal:7077 workspace/SparkNeo4jSample.py
```

This is the format provided by the [Spark master](http://52.213.206.26:8080/). Tutorial steps can be found [here](https://github.com/tomncooper/CSC8101-Documentation/blob/master/spark/python-stub/python-deployment.md#cluster-deployment). You should be able to specify the master option from your script too, following the above docs.

Let us know if this helps.

**Comment by tomncooper** [comment]
My bad, I missed the spark part off the master string. I will alter the docs now.

**Comment by cheburan** [comment]
Thanks guys. "spark://52.213.206.26:7077" helped!
