### ISSUE TITLE
Spark Streaming: Correct approach for combining outputs from different map reduce operations on same page visit?

### ISSUE THREAD

**Issue by alexbfree** [tomncooper/CSC8101-Documentation#21]
Hi
I'm just trying to get my head around how to use Spark in practice - specifically how to recombine the outputs of different map/reduce operations.
I'm on Task 5, I have got a map reduce operation that produces my hit counts, having earlier got a different map reduce operation that finds the batch start time, and of course the original map that gets the dictionary version of the incoming JSON string.

What is puzzling me is to understand the best practice for bringing these various pieces together in order that I might complete the 
```
# row_rdd_example = rrd_example.map(lambda x: Row(field1=x[0],
#                                                field2=x[1],
#                                                field3=x[2],
#                                                field4=x[3],
#                                                field5=x[4]))
```
part. I have 3 rows in one RDD (the dictionary), one in a different reduce output (the batch start time), and one in a different RDD (the count).

The challenge that I have is that certain reduce operations seem to effectively require me to throw away certain data, because the reduce function needs to have only certain data present.
For example, `reduceByKey(lambda x, y: x + y)` requires tuples... so I can no longer keep my full dictionary version of the page visit around. And when calculating the batch start time, I have to throw pretty much everything away.

So, I guess I need to rejoin this data together.

I thought about using a unique key, then do a RDD join to join all my bits of data together (the batch start time, the hit count, the original dictionary record, etc). I am not sure if this is safe - can I count on this join not picking up data from another page hit record if I use the same key every time? (and if not, how can I generate a unique key per page hit without also losing the original data which of course is the problem I am trying to solve)

I thought about using `UpdateStateByKey`, to store all the stuff to do with this batch in one place... but I can't figure out enough from the doc to understand the scope of this storage, how would I wipe it when I am finished with each batch, etc... not sure if this is even the right way to go.

I found some stuff about broadcast variables, but that seems too heavy duty for what I am trying to do here.

I am also unclear on whether the general approach of collecting all the data for the batch together after reducing it is "allowed". I know the whole point of map-reduce is to treat everything individually so we don't bulk masses of data together in one place. Is it safe to aggregate all the data in a batch together after reduction, simply because we know the batches should be small - max 2 minutes? or do I need to find some way to do all the processing with just map and reduce operations?

Hope you can provide some guidance. I can probably cobble something together but I don't feel well equipped to assess the best way forward, from a "best practice" standpoint!

Ideally this is the sort of question I could have asked in a lab practical, but I didn't get this far in the time available... 

Cheers.

**Comment by tomncooper** [comment]
You are never throwing information away in a spark job, like in batch RDDs every intermediate stage is retained. If you assign intermediate dstreams as variables you can access them at a later stage.

One of the first tasks is to create a dstream of dictionaries from the json messages. This dstream is still available at later stages if you need to refer back to it. 

As to the issue of using retaining information in tuples, you can define what information is in these and order is maintained (within the tuple) so you will always know what information is in what index of the tuple (a tuple can be any length). For reduce and join operations they usually take the form `(k, v)`, but `v` can be anything you like, so you could have `(client_id, (<every other value from the dictionary as a tuple, dict or list>))` and retain all the information you want after a join operation.

`UpdateStateByKey` is the wrong approach as this is for use across window periods and we only want aggregations within each window. Also broadcast variables are not, as you have identified, the right approach. As it says in the documentation a join is the best way to combine information from seperate dstreams.

**Comment by alexbfree** [comment]
Thank you, that was really helpful. Sorry my issue was a bit long, I am still learning as I go, and was obviously confused about a few things.

I understand that I can assign intermediate dstreams as variables to access them at a later stage. indeed I am doing so. The challenge is how to keep these connected to each other.

For example, to calculate the minimum timestamp using reduceByKey, the source dictionary data must be remapped to a tuple of string key and an int counter. So the `(client_id, (<every other value from the dictionary as a tuple, dict or list>))` approach you mentioned wouldn't be possible. It seems the only way to reconnect the calculated minimum timestamp to the unaltered RDD of dictionaries is to join on some arbitrary key... ie there is no way to pass the minimum timestamp AND the dictionary data down the chain.

If I am wrong and there is some way to pass it down the chain then please let me know - will assume not if I don't hear anything.

Cheers

**Comment by tomncooper** [comment]
A join on a common key between min timestamp dstream and another dstream is a valid approach, you may have to create a common key for the join to work.

**Comment by alexbfree** [comment]
OK thanks.
