### ISSUE TITLE
Cassandra/Streaming: Do we need to do anything about overlapping windows?

### ISSUE THREAD

**Issue by alexbfree** [tomncooper/CSC8101-Documentation#22]
In the Cassandra/Streaming courseworks we are dealing with overlapping windows of data... should we be doing anything about the fact that each record will appear in two windows? to avoid everything being doubled? I didn't see any specific requirements on this (though it's possible I missed something). Thanks

**Comment by tomncooper** [comment]
No need to worry about replicated data in overlapping windows.

**Comment by alexbfree** [comment]
Thanks; out of interest is that because the system handles it for us - or that technically it is an issue but is out of scope for our assignment?

**Comment by tomncooper** [comment]
The second one
