### ISSUE TITLE
Cassandra task wording

### ISSUE THREAD

**Issue by allandarity** [tomncooper/CSC8101-Documentation#24]
Hi,

For the Cassandra Tasks, such as Task 2, does the query have to do everything required on its own? 

Or, can we use a function that takes the results from a cql query and then manipulates it to match the task i.e. in task 2 take the information from the database and then use a map to create unique keys and then print that as the answer?

**Comment by tomncooper** [comment]
For the Cassandra coursework Task 1 and 2 should be complete using only CQL queries. You should use the table schema to format the data such that your queries return the required information.

For Cassandra Task 3 you will need to combine information, returned by the queries in task 1 and 2, in a client side program to produce the recommendations.

**Comment by animaala** [comment]
For Task 2, I have some confusion on the wording. Do we need to count the visits for each page, or the visits to each page by unique clients?

**Comment by tomncooper** [comment]
The second one.
