### ISSUE TITLE
Spark Streaming Kafka broker

### ISSUE THREAD

**Issue by JonathanRaine** [tomncooper/CSC8101-Documentation#27]
I am currently doing the resit for this module and the json given to me by the Kafka broken in my code is returning "{"storageLevel":{"valid":false},"numPartitions":0,"checkpointFile":{"present":false},"checkpointed":false,"empty":true}".
I was wondering if it had be reconfigured to output this, or whether I am doing something incorrectly.

**Comment by PetoMichalak** [comment]
Hi Jonathan,

thanks for contacting us. I've started a stream generator and one of the kafka brokers for you.

Try to connect to it on this address: 34.248.5.122

Both the 'dev-stream' and 'production' topics should be available for you to test your solution on.

Let us know if this helped.

**Comment by JonathanRaine** [comment]
I am still receiving the same json unless my parsing is incorrect. Is the port still 2181?

**Comment by PetoMichalak** [comment]
I've checked and yes the port is open. This is the same kafka broker we've used during the module. I was surprised that you were getting some response even when no brokers were up. 

Could you copy your connection code snippet, so we could look at it here?

**Comment by JonathanRaine** [comment]
SparkConf conf = new SparkConf()
        .setMaster("local[2]")
        .setAppName("App")
        .set("spark.cassandra.connection.host","localhost")
        .set("spark.cassandra.connection.keep_alive_ms", "60000");
    	
    	JavaStreamingContext jssc = new JavaStreamingContext(conf, Durations.seconds(2));String topicName = "dev-stream";  
    	partitions.put(topicName, 1);    	
    	
    	JavaPairReceiverInputDStream<String, String> kafkaStream =
    		     KafkaUtils.createStream(jssc, "34.248.5.122:2181", "160554490", partitions);

that is the code i'm using to connect to the broker

**Comment by saleh-SHA** [comment]
Hi Jonathan,

Would you try to change the port from 2181 to 9092? Port 2181 is used for connecting to Zookeeper server while Kafka uses port 9092.

**Comment by JonathanRaine** [comment]
I changed the port it was using and instead of getting that json message, I now get "MapPartitionsRDD[2] at map at App.java:61" as the value returned from my map function. I am also now unable to use the windowed dstream as i get this message:
"Time 1494510834000 ms is invalid as zeroTime is 1494510832000 ms , slideDuration is 60000 ms and difference is 2000 ms"

**Comment by JonathanRaine** [comment]
I have fixed being able to receive the json messages but it is still giving me "{"storageLevel":{"valid":false},"numPartitions":0,"checkpointFile":{"present":false},"checkpointed":false,"empty":true}". Even after changing the port to 9092
