### ISSUE TITLE
Memory problems and time to run ALS.train

### ISSUE THREAD

**Issue by Tom-Ryder** [tomncooper/CSC8101-Documentation#3]
I am attempting to run ALS.train w/ parameters as suggested on an 80/20 split of the data. I have not as of yet been able to obtain a result, with the computation taking an extremely long time. I have, as suggested in a previous issue, increased my memory size - but to no avail.

I have received a number of system warnings from my vm's terminal, the latest being: 

"[Stage 20:>                                                        (0 + 2) / 37]17/02/14 13:28:31 WARN LAPACK: Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
'

This was previously:

"17/02/14 13:10:59 WARN MemoryStore: Failed to reserve initial memory threshold of 1024.0 KB for computing block rdd_27_67 in memory."

before increasing the memory size.

**Comment by PetoMichalak** [comment]
Hi,

the warning you describe doesn't prevent the model from completion - Spark is warning you that the operation might take longer as native accelerators are not present. The model with 80M records will take some time to build. However, this big data analytics task shouldn’t take longer than 30 minutes on m4.large AWS instance with modified pyspark settings.

I would suggest you revisit your code to make sure that you are creating a [Rating](https://spark.apache.org/docs/latest/api/java/org/apache/spark/mllib/recommendation/Rating.html) record with correct information AND in the proper order as per docs. 

You could also take only a [sample](https://spark.apache.org/docs/1.6.2/api/java/org/apache/spark/rdd/RDD.html#sample(boolean,%20double,%20long)) of the ratings file (e.g. ~5M records) for which the model should take only couple of minutes to complete on your student VM.

Another approach, as described by Hugo during [his lecture]( https://blackboard.ncl.ac.uk/webapps/ppto-PanoptoCourseTool-BBLEARN/Content.jsp?course_id=_76452_1&mode=cpview) (Tuesday 07, last half hour) on this topic, is tweaking the parameters you are passing to the model. But be careful not to lower them too much as this will decrease the model prediction power (which you’ll be able to catch comparing RMSE at later stage).

Try to do a prediction on a sample user from this model to see results. If you are happy, you could proceed with the coursework and come back to this part later to deploy it to the cluster with full dataset which should return results faster.

Let us know if you have further questions or if the model doesn’t work even with the smaller dataset.

**Comment by Tom-Ryder** [comment]
I subsetted the data set to just under a million, and I am pretty certain my formatting of the Rating RDD is correct (as per the example on spark's site). The ALS.fit took circa 8 mins to run on this data set 80 times as small as the proper training split. I don't know if the ALS scales linearly, but assuming it does, that's 10 hours. 

Edit: including running predictions, total process took 30 mins. Printing the the output of the predicition gives me what I'd expect so I'm probably doing it correctly. Obtain valid MSE also.

**Comment by Tom-Ryder** [comment]
The code I'm using:
```
<code snippet removed>
```

**Comment by kathryn-garside** [comment]
I am having the same problem - a training set of ~800 ratings (!!) takes 10-15 mins to complete, with predictions and computing the MSE taking even longer.

**Comment by PetoMichalak** [comment]
Hi,

[Spark RDD API](http://spark.apache.org/docs/2.1.0/api/python/pyspark.html) offers a variety of useful functions. Are you splitting the dataset using one of them, or have you written your own implementation, which might not be as efficient?

You could also time sections of your code to see which parts actually take the longest to execute e.g.:

```python
from datetime import datetime
start_time = datetime.now()

this_takes_time()

print("It took %.2f s to complete." % (datetime.now() - start_time).total_seconds())
```

**Comment by kathryn-garside** [comment]
I don't think the splitting of the data is the problem. I can split using the inbuilt functions and look at the new data quite quickly. 
`ratingsSubset=ratings.sample(0.00001,1)`
`trainData,testData = ratingsSubset.randomSplit([0.8, 0.2],seed=1)`

**Comment by PetoMichalak** [comment]
Closing this issue as resolved by this [FAQ: My program is taking a long time to execute](https://github.com/tomncooper/CSC8101-Documentation/blob/master/spark/spark-faq.md#my-program-is-taking-a-long-time-to-execute).

Please create another thread if above is not satisfactory.
