### ISSUE TITLE
Connection to notebook.

### ISSUE THREAD

**Issue by gstama** [tomncooper/CSC8101-Documentation#4]
I have a problem about connecting to the notebook, I have tried all the general solutions but the issue does not seem to go away, the last measure will be to create a new instance but that will not allow me to keep my code.

**Comment by tomncooper** [comment]
Hi George,

We are trying to track down what the issue might be.

Have you run a apt-get update on the VM since launch? 

In the mean time you can run a terminal version of the notebook by running:

`$ ~/scripts/ipyspark.sh`

More details are given in the [FAQ](http://tomcooper.org.uk/CSC8101-Documentation/spark/spark-faq.html)

**Comment by tomncooper** [comment]
George, 

Can you let me know the name of your VM and I'll check its security group settings.

**Comment by gstama** [comment]
Hey Tom,

CSC8101-2016-17-160343850

Cheers

On 15 Feb 2017, at 16:12, Thomas Cooper <notifications@github.com<mailto:notifications@github.com>> wrote:


George,

Can you let me know the name of your VM and I'll check its security group settings.

**Comment by tomncooper** [comment]
Your VM is in the correct security group and has all the correct ports open. I have re-assigned it to the same group in the hope that might refresh whatever config is not working.

Have you always been able to ssh into the machine?

**Comment by gstama** [comment]
Yes I can ssh, I am currently trying to work in the pyspark in the cli, but can not connect to the notebook.

**Comment by PetoMichalak** [comment]
Hi,

I have changed the default port which iPython notebook binds to on your VM to 8989. I have run it as per instructions:

```bash
$ pyspark
```

and then connect through web browser as follows:

```
http://<your_public_ip>:8989/
```

Everything seemed to work and I could run Spark commands as usual.

Please give it a go and let us know if you have still issues. I wasn't able to find any other program on your VM, which would sit on the previous port (8888), but the change I made should work for you. Sorry for the inconvenience.

**Comment by gstama** [comment]
Thanks Peter, I have created a second VM (v2.0) and continued working there, I will give your solution a go and copy my code back to the old VM if need be.
